# Media Manager - Drive Setup Script
# Run this script to generate docker-compose.override.yml with your local drives mounted
# Re-run whenever your drive configuration changes

Write-Host ""
Write-Host "=== Media Manager Drive Setup ===" -ForegroundColor Cyan
Write-Host ""

# Get all accessible filesystem drives
$drives = Get-PSDrive -PSProvider FileSystem | Where-Object { $_.Root -ne "" }

if (-not $drives) {
    Write-Host "No drives found!" -ForegroundColor Red
    exit 1
}

Write-Host "Found drives:" -ForegroundColor Green
foreach ($drive in $drives) {
    $letter = $drive.Name.ToLower()
    $root = $drive.Root
    $used = if ($drive.Used) { [math]::Round($drive.Used / 1GB, 1) } else { "?" }
    $free = if ($drive.Free) { [math]::Round($drive.Free / 1GB, 1) } else { "?" }
    Write-Host "  $($drive.Name): ($root) - Used: ${used}GB, Free: ${free}GB" -ForegroundColor White
}

Write-Host ""
Write-Host "Generating docker-compose.override.yml..." -ForegroundColor Cyan

# Build the override file content
$lines = @(
    "# Auto-generated by setup.ps1 - DO NOT EDIT MANUALLY",
    "# Re-run setup.ps1 if your drive configuration changes",
    "# Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')",
    "",
    "services:",
    "  backend:",
    "    volumes:"
)

foreach ($drive in $drives) {
    $letter = $drive.Name.ToLower()
    # Normalize path to forward slashes for Docker
    $root = $drive.Root -replace '\\', '/'
    # Remove trailing slash if present (except root)
    $root = $root.TrimEnd('/')
    # For Docker Desktop on Windows, use the /mnt/drives/ convention
    $mountPath = "/mnt/drives/$letter"

    # Determine drive type
    $driveType = "Local"
    try {
        $wmiDrive = Get-WmiObject -Query "SELECT DriveType FROM Win32_LogicalDisk WHERE DeviceID='$($drive.Name):'" -ErrorAction SilentlyContinue
        if ($wmiDrive) {
            switch ($wmiDrive.DriveType) {
                2 { $driveType = "Removable" }
                3 { $driveType = "Local" }
                4 { $driveType = "Network" }
                5 { $driveType = "CD-ROM" }
                default { $driveType = "Unknown" }
            }
        }
    } catch {
        # Ignore WMI errors
    }

    $comment = "      # Drive $($drive.Name): ($driveType)"
    $lines += $comment
    $lines += "      - `"$($root)/:$mountPath`""
}

# Always include the data and scripts volumes
$lines += "      - ./data:/data"
$lines += "      - ./backend/scripts:/app/scripts"

$content = $lines -join "`n"

# Write the file
$overridePath = Join-Path $PSScriptRoot "docker-compose.override.yml"
Set-Content -Path $overridePath -Value $content -Encoding UTF8

Write-Host ""
Write-Host "Created: docker-compose.override.yml" -ForegroundColor Green
Write-Host ""
Write-Host "Drive mount summary:" -ForegroundColor Cyan
foreach ($drive in $drives) {
    $letter = $drive.Name.ToLower()
    Write-Host "  $($drive.Name):\ --> /mnt/drives/$letter" -ForegroundColor White
}

Write-Host ""
Write-Host "Next steps:" -ForegroundColor Yellow
Write-Host "  1. Run: docker-compose up -d" -ForegroundColor White
Write-Host "  2. Open: http://localhost:45681" -ForegroundColor White
Write-Host ""
Write-Host "WARNING: Re-run this script if you connect/disconnect drives" -ForegroundColor Yellow
Write-Host ""
