# Media Manager - Drive Setup Script
# Run this script to generate docker-compose.override.yml with your local drives mounted
# Re-run whenever your drive configuration changes

Write-Host ""
Write-Host "=== Media Manager Drive Setup ===" -ForegroundColor Cyan
Write-Host ""

# Get all accessible filesystem drives
$drives = Get-PSDrive -PSProvider FileSystem | Where-Object { $_.Root -ne "" }

if (-not $drives) {
    Write-Host "No drives found!" -ForegroundColor Red
    exit 1
}

Write-Host "Found drives:" -ForegroundColor Green
foreach ($drive in $drives) {
    $letter = $drive.Name.ToLower()
    $root = $drive.Root
    $used = if ($drive.Used) { [math]::Round($drive.Used / 1GB, 1) } else { "?" }
    $free = if ($drive.Free) { [math]::Round($drive.Free / 1GB, 1) } else { "?" }
    Write-Host "  $($drive.Name): ($root) - Used: ${used}GB, Free: ${free}GB" -ForegroundColor White
}

Write-Host ""
Write-Host "Generating docker-compose.override.yml..." -ForegroundColor Cyan

# Load manual overrides if they exist (user-editable, wins over auto-detection)
$dataDir = Join-Path $PSScriptRoot "data"
if (-not (Test-Path $dataDir)) { New-Item -ItemType Directory -Path $dataDir | Out-Null }
$overridesPath = Join-Path $dataDir "drives-overrides.json"
$overrides = @{}
if (Test-Path $overridesPath) {
    try {
        $raw = Get-Content $overridesPath -Raw | ConvertFrom-Json
        $raw.PSObject.Properties | ForEach-Object { $overrides[$_.Name.ToLower()] = $_.Value }
        Write-Host "  Loaded overrides from drives-overrides.json" -ForegroundColor Gray
    } catch {
        Write-Host "  WARNING: Could not parse drives-overrides.json — skipping overrides" -ForegroundColor Yellow
    }
}

# Detect drive types, build metadata map
$driveMeta = @{}
foreach ($drive in $drives) {
    $letter = $drive.Name.ToLower()

    # Priority 1: DisplayRoot is set → this is an SMB-mapped network drive
    if (-not [string]::IsNullOrEmpty($drive.DisplayRoot) -and $drive.DisplayRoot -match '^\\\\') {
        $driveType  = "Network"
        $volumeName = $drive.DisplayRoot   # show UNC path as subtitle
    } else {
        # Priority 2: WMI for Removable / CD-ROM (type 3 = Local is unreliable for iSCSI/NAS)
        $driveType  = "Local"
        $volumeName = ""
        try {
            $wmiDrive = Get-WmiObject -Query "SELECT DriveType,VolumeName FROM Win32_LogicalDisk WHERE DeviceID='$($drive.Name):'" -ErrorAction SilentlyContinue
            if ($wmiDrive) {
                switch ($wmiDrive.DriveType) {
                    2 { $driveType = "Removable" }
                    5 { $driveType = "CD-ROM" }
                    # 3 = Local (also used by iSCSI - override via drives-overrides.json if needed)
                    # 4 = Network (WMI catches standard mapped drives; DisplayRoot catches the rest)
                }
                $volumeName = if ($wmiDrive.VolumeName) { $wmiDrive.VolumeName } else { "" }
            }
        } catch {}
    }

    # Priority 3: Manual override wins over everything
    if ($overrides.ContainsKey($letter)) {
        $driveType = $overrides[$letter]
    }

    $driveMeta[$letter] = @{
        type        = $driveType
        volume_name = $volumeName
        root        = $drive.Root
    }
}

# Print what was detected so misclassifications are visible
Write-Host "Drive type detection:" -ForegroundColor Cyan
foreach ($drive in $drives) {
    $letter = $drive.Name.ToLower()
    $m = $driveMeta[$letter]
    $overrideFlag = if ($overrides.ContainsKey($letter)) { " [override]" } else { "" }
    $color = switch ($m.type) { "Network" { "Cyan" } "Removable" { "Yellow" } "CD-ROM" { "Yellow" } default { "White" } }
    Write-Host "  $($drive.Name): $($m.type)$overrideFlag  $($m.volume_name)" -ForegroundColor $color
}
Write-Host ""
Write-Host "  If a drive type is wrong, create data\drives-overrides.json:" -ForegroundColor Gray
Write-Host '  { "m": "Network", "s": "Network" }' -ForegroundColor Gray
Write-Host "  Then re-run this script." -ForegroundColor Gray
Write-Host ""

# Write drives-meta.json so the backend can expose drive types to the UI
$metaPath = Join-Path $dataDir "drives-meta.json"
$driveMeta | ConvertTo-Json -Depth 3 | Set-Content -Path $metaPath -Encoding UTF8
Write-Host "  Wrote drive metadata: $metaPath" -ForegroundColor Gray

# Build the override file content
$lines = @(
    "# Auto-generated by setup.ps1 - DO NOT EDIT MANUALLY",
    "# Re-run setup.ps1 if your drive configuration changes",
    "# Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')",
    "",
    "services:",
    "  backend:",
    "    volumes:"
)

foreach ($drive in $drives) {
    $letter = $drive.Name.ToLower()
    $meta   = $driveMeta[$letter]
    # Normalize path to forward slashes for Docker
    $root = $drive.Root -replace '\\', '/'
    # Remove trailing slash if present (except root)
    $root = $root.TrimEnd('/')
    # For Docker Desktop on Windows, use the /mnt/drives/ convention
    $mountPath = "/mnt/drives/$letter"

    $comment = "      # Drive $($drive.Name): ($($meta.type))"
    $lines += $comment
    $lines += "      - `"$($root)/:$mountPath`""
}

# Always include the data and scripts volumes
$lines += "      - ./data:/data"
$lines += "      - ./backend/scripts:/app/scripts"

$content = $lines -join "`n"

# Write the file
$overridePath = Join-Path $PSScriptRoot "docker-compose.override.yml"
Set-Content -Path $overridePath -Value $content -Encoding UTF8

Write-Host ""
Write-Host "Created: docker-compose.override.yml" -ForegroundColor Green
Write-Host ""
Write-Host "Drive mount summary:" -ForegroundColor Cyan
foreach ($drive in $drives) {
    $letter = $drive.Name.ToLower()
    Write-Host "  $($drive.Name):\ --> /mnt/drives/$letter" -ForegroundColor White
}

Write-Host ""
Write-Host "Next steps:" -ForegroundColor Yellow
Write-Host "  1. Run: docker-compose up -d" -ForegroundColor White
Write-Host "  2. Open: http://localhost:45681" -ForegroundColor White
Write-Host ""
Write-Host "WARNING: Re-run this script if you connect/disconnect drives" -ForegroundColor Yellow
Write-Host ""
